### PR TITLE
#124 added bootstrap carousel on banner

### PR DESCRIPTION
**Pull request by Libbna**
Before the banner was still and now it should slide with fade effect. 

Expected result: 
image

### CODE REVIEW

**Review by omkar-pd — CHANGES_REQUESTED** [review]
Getting this error.
image

**Review by vbadkar — CHANGES_REQUESTED** [review]
image
Getting this error

**Comment by Libbna** [comment]
@omkar-pd @vbadkar can you test again? I have updated the code.

**Comment by omkar-pd** [comment]
working now. 
but images are too big and controllers aren't visible can you fix that.
image

**Comment by Libbna** [comment]
> working now. but images are too big and controllers aren't visible can you fix that. image

Sure, will do that.

**Comment by Libbna** [comment]
@omkar-pd can you please test the PR again? I have made the changes as requested.

**Review by omkar-pd — APPROVED** [review]
Looking good now !
image

**Review by vbadkar — APPROVED** [review]
Looking good and working as intended
image

**Review by RChaubey16 — APPROVED** [review]
LGTM

Screenshot from 2022-01-28 16-20-42

**Pull request merged**
