### PR TITLE
#198: Fixed the issue with redirection, now the logo appear without refresing the page [WIP]

### PR DESCRIPTION
**Pull request by vbadkar**
Steps to test:

1. Login with admin access
2. Goto config page
3. Add a new logo
4. Check whether the logo is changed immediately after clicking on the submit button

Note:- The message is still not getting displayed*

### CODE REVIEW

**Review by RChaubey16 — CHANGES_REQUESTED** [review]
* Logo is getting updated. No need to refresh the page. But the favicon is not getting updated.

Screenshot from 2022-01-13 07-57-43

**Comment by vbadkar** [comment]
> * Logo is getting updated. No need to refresh the page. But the favicon is not getting updated.
> 
> Screenshot from 2022-01-13 07-57-43

Synced the PR with latest changes, @RChaubey16 Can you please check now?, the favicon is also changing.

**Review by RChaubey16 — APPROVED** [review]
Working perfect now !

Screenshot from 2022-01-13 16-57-22

**Review by omkar-pd — APPROVED** [review]
Working fine !

image

**Review by AkshayDalvi15 — APPROVED** [review]
Working fine, no need to refresh the page.

image

**Pull request merged**
