### PR TITLE
#157: Styled the users list in admin view

### PR DESCRIPTION
**Pull request by RChaubey16**

### CODE REVIEW

**Comment by Libbna** [comment]
Screenshot from 2022-01-05 18-37-01

@RChaubey16  it is looking like this on my site. Is this fine?

**Comment by RChaubey16** [comment]
yup. It is fine.

**Comment by Libbna** [comment]
Approved.

**Review by vbadkar — APPROVED** [review]
Looks good
Screenshot from 2022-01-05 18-48-43
Approved..

**Pull request merged**
