### PR TITLE
#239: fixed card height

### PR DESCRIPTION
**Pull request by omkar-pd**
**Testing Steps:**

- Go to the home page and check the height of the cards.
- check the height of the cards on smaller devices as well.
- Go to the article page and check the height of the on smaller devices as well.
- Check for the hover effects as well.
- Refer to Screenshot.

**Homepage:**
image

**Article Page:**
image

### CODE REVIEW

**Review by Mspiro — CHANGES_REQUESTED** [review]
image
If the card not have any summary then it will use min-height, and the card height is looks like mismatch. 

what if we try to fetch summary as trimed meta data only for two lines and then only show those line insted of showing 4 to 5 lines of summary in card. because if user create any article then he/she write minimum one line of blog. So if we take summary as 1 line or 2 line so our card not be affected. 
If it is not very necessary then it is good to go. 
image

**Comment by omkar-pd** [comment]
> image If the card not have any summary then it will use min-height, and the card height is looks like mismatch.
> 
> what if we try to fetch summary as trimed meta data only for two lines and then only show those line insted of showing 4 to 5 lines of summary in card. because if user create any article then he/she write minimum one line of blog. So if we take summary as 1 line or 2 line so our card not be affected. If it is not very necessary then it is good to go. image

@Mspiro  I have fixed that, can you check again?

**Review by Mspiro — APPROVED** [review]
image
Looks good now.

**Review by RChaubey16 — APPROVED** [review]
LGTM

Screenshot from 2022-01-21 16-39-26


Screenshot from 2022-01-21 16-39-33

**Review by vbadkar — APPROVED** [review]
Working fine on my side
**Homepage:**
image

**Article details page:**
image

**Pull request merged**
