### PR TITLE
#288: Fixed issues in category section

### PR DESCRIPTION
**Pull request by omkar-pd**
**Testing Steps:**

- Go to the Category Section and change to the category which has multiple articles.
- Check for Alignment of cards.
- And make sure extra content like `", "` does not appear.
- Refer to the following Screenshot.

image

### CODE REVIEW

**Comment by RChaubey16** [comment]
@omkar-pd The section looks like this, Is this correct??

Screenshot from 2022-02-22 15-46-31

**Comment by omkar-pd** [comment]
> @omkar-pd The section looks like this, Is this correct??
> 
> Screenshot from 2022-02-22 15-46-31

no, There should be margin between two rows of cards.
like this: 
image

**Review by Libbna — CHANGES_REQUESTED** [review]
image

the output is different on my side. Can you please check?

**Review by Libbna — APPROVED** [review]
image

Working now.

**Review by vbadkar — APPROVED** [review]
Working fine and margin issue is also resolved.
image

**Pull request merged**
