### PR TITLE
#195 made favicon dynamic

### PR DESCRIPTION
**Pull request by Libbna**
For Testing: 
- On config page, upload a logo and add a site name. 
- After submitting the form, the favicon will also get changed same as logo. 

For ref: 
image

### CODE REVIEW

**Review by RChaubey16 — APPROVED** [review]
Working on my end !

Screenshot from 2022-01-12 09-28-04

**Review by omkar-pd — APPROVED** [review]
image

Working fine !

**Review by vbadkar — APPROVED** [review]
image
Working on my side too

**Comment by RChaubey16** [comment]
Got 3 approvals. Merging.

**Pull request merged**
