### PR TITLE
#189: Solved the issue with some extra margin below footer in config page

### PR DESCRIPTION
**Pull request by RChaubey16**
* Solved the issue of extra margin present on `config` page.
* The class `content-region` had a  height of `100vh` which was causing the issue.
* Hence removed it and checked for all the side effects it may have caused. FYI, none found.
* Screenshot => 

Screenshot from 2022-01-11 15-54-21

### Testing Steps : 
1. Login as admin.
2. Go to config tab.
3. Scroll down to the very bottom of the page.
4. If no extra margin or white space is present, then everything is working fine.

### CODE REVIEW

**Comment by omkar-pd** [comment]
image

Working !

**Review by omkar-pd — APPROVED** [review]
working

**Review by vbadkar — APPROVED** [review]
image
Issue resolved, working fine on my side

**Review by Libbna — APPROVED** [review]
image
Looks good on my site.

**Pull request merged**
