### PR TITLE
#222: Changed the styling for Menu and Block display page

### PR DESCRIPTION
**Pull request by vbadkar**
Steps to test:
* Login and goto users display page see the styling 
* Go to block and menu display pages and see if styling for those pages are similar

### CODE REVIEW

**Comment by Libbna** [comment]
image

@vbadkar this is how it should look?

**Comment by vbadkar** [comment]
> image
> 
> @vbadkar this is how it should look?

yes

**Review by RChaubey16 — APPROVED** [review]
Working FIne !

Screenshot from 2022-01-14 16-07-58

**Review by Libbna — APPROVED** [review]

**Review by Mspiro — APPROVED** [review]
image
image
Looks good at my end

**Pull request merged**
