### PR TITLE
#145 updated the getmessage method on msgGen service file -

### PR DESCRIPTION
**Pull request by Libbna**
For testing try to create an article, the success message you will see is coming from message service. Try to change the message in Controllers/Article.php - insertArticle method.

### CODE REVIEW

**Review by RChaubey16 — APPROVED** [review]
LGTM

Screenshot from 2022-02-22 15-39-52

**Review by omkar-pd — CHANGES_REQUESTED** [review]
@Libbna  can you take the fresh pull and commit again. some of the files are missing in your PR. eg category.js

**Comment by Libbna** [comment]
> 

@omkar-pd The category.js file is there on my end. Can you please attach a screenshot? 

> @Libbna can you take the fresh pull and commit again. some of the files are missing in your PR. eg category.js

**Review by omkar-pd — APPROVED** [review]
Working fine now.
image

**Pull request merged**
