### PR TITLE
#221: Search feature Implementation.

### PR DESCRIPTION
**Pull request by RChaubey16**
* Added search template.
* Added controller and model methods that handle the search request.
* Displayed the search results on search template..

* Testing steps
    * Type the query in search input field.
    * Hit enter or click the search icon.
    * Results or no results page should get rendered.
    * This search works for misspelled queries as well.
    
    * Also, Go to article page, scroll down and click on any category in the category.
    * Articles related to the category should be listed as a result.

### CODE REVIEW

**Comment by RChaubey16** [comment]
* Everything is working fine and has been implemented. Go ahead, test and review the PR.

**Review by omkar-pd — APPROVED** [review]
**Search Results:**
image

**Working with categories as well:_**
image

**Review by Libbna — APPROVED** [review]
image

Working when I am not logged in. Requested changes.

**Review by Libbna — CHANGES_REQUESTED** [review]
LoggedIn user's name doesn't show up on search page instead Login button shows. Can you please fix it?

**Comment by RChaubey16** [comment]
@Libbna The issue has been fixed. Can you check it??

**Review by Libbna — APPROVED** [review]
image

Working now!

**Review by Mspiro — APPROVED** [review]
image
Working Fine

**Pull request merged**
