### PR TITLE
#213:  Add search icon to navbar.

### PR DESCRIPTION
**Pull request by RChaubey16**
* Added search icon and input field to navbar.
* Also solved the error ocurring on `localhost/custom_cms/` root route.
* The root route is now getting redirected to home page.
* Steps for testing : 
   * The navbar should contain the search input field and button.
   * Go to `localhost/custom_cms/` root route.
   * The root route should get redirected to `/home` route automatically.

* Refer screenshot for search icon and input field.

Screenshot from 2022-01-13 15-55-34

### CODE REVIEW

**Review by vbadkar — APPROVED** [review]
1. Root route is working as intended 
2. Search bar is also added 
image
Looks good, approved

**Review by omkar-pd — APPROVED** [review]
Working fine!

- Redirecting to home route.
- Search Field is visible.

image

**Review by Libbna — APPROVED** [review]
image
looks fine on my end.

**Review by AkshayDalvi15 — APPROVED** [review]
Working fine,
search bar is visible and working...
image

**Pull request merged**
