### PR TITLE
#291- Scroll top top feature added

### PR DESCRIPTION
**Pull request by AkshayDalvi15**
**Testing steps:**
1) Scroll Down on any page.
2) look if you can see the Top button on the right bottom side.
3) Click on the Top button and it will automatically scroll to top.

### CODE REVIEW

**Comment by RChaubey16** [comment]
@AkshayDalvi15 
* The feature is working but the styling is not getting applied, the button is appearing at the bottom of the page. 
* The changes of `main.css` have not been pushed I think so. Can you confirm this.
* Refer screenshot :

Screenshot from 2022-02-23 18-58-45

**Review by Libbna — CHANGES_REQUESTED** [review]
image
 Perfectly working on my end. 
- But can you change the button icon - instead of "top" can you add "up-arrow" or something?
- And can you increase the visibility distance of top button. like >100px or 120px?  @AkshayDalvi15

**Review by vbadkar — APPROVED** [review]

**Review by vbadkar — APPROVED** [review]
Working on my side 
image
@AkshayDalvi15 just sync with the lastest pull

**Review by Libbna — APPROVED** [review]
image

Yes, it's fine now.

**Review by omkar-pd — APPROVED** [review]
Working fine !

**Review by vbadkar — APPROVED** [review]
Synced with the master, ready to merge

**Pull request merged**
