### PR TITLE
#142: Dynamic footer feature added.

### PR DESCRIPTION
**Pull request by RChaubey16**
* Added the feature of dynamic footer.
* Testing Steps : 
    1. Login as admin.
    2. Go to config tab.
    3. The `Footer Details` section should be visible in the form.
    4. Add all the details in the form. (From logo to email of the footer).
    5. Submit the form.
    6. The updated data should be visible in footer and the database as well.

* Expected testing results : 

Screenshot from 2022-01-24 13-31-06

Screenshot from 2022-01-24 13-31-23

### CODE REVIEW

**Review by vbadkar — APPROVED** [review]

**Review by vbadkar — CHANGES_REQUESTED** [review]
@RChaubey16 Can you please add the database file or the table we have to add for this to work?

**Comment by RChaubey16** [comment]
Database file for footer table
[footerDetails.zip](https://github.com/Libbna/CUSTOM-CMS/files/7924991/footerDetails.zip)

Add this file in the `custom_cms` database.

**Review by Libbna — APPROVED** [review]
image

Working on my end.

**Review by vbadkar — APPROVED** [review]
image
Working fine on my side too!

**Comment by omkar-pd** [comment]
Getting this error on submit.
image

**Review by omkar-pd — APPROVED** [review]
working fine

**Pull request merged**
